Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 256
      Handler: functions.GetCurrency
      CodeUri: D:\workspace\exchange-provider-aws\HelloWorldFunction
      Runtime: java11