Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: functions.CurrencyDataFetcher
      CodeUri: D:\workspace\exchange-provider-aws\HelloWorldFunction
      Runtime: java11